Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 99

AllCops:
  Exclude:
    - "features/support/env.rb"

GlobalVars:
  AllowedVariables:
    - $driver

Metrics/LineLength:
  Max: 100
